version: '3.9'

services:

  redis-server:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
    networks:
      - omimporter-network

  omimporter:
    depends_on:
      - redis-server

    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - omimporter-network

networks:
  omimporter-network:

volumes:
  cache:
    driver: local
